site_name: Galaxea
site_url: https://userguide-galaxea.github.io/userguide-galaxea/
repo_url: https://github.com/userguide-galaxea/userguide-galaxea
site_description: "Galaxea"
copyright: Copyright &copy; 2023 - 2024 Galaxea
site_author: Galaxea Inc

theme:
    name: material
    logo: assets/logo.png
    palette:
        primary: black
    font:
        code: Roboto Mono
plugins:
    - search:
        enabled: true
features:
    - search.highlight
    - search.inline
    - search.excerpt
    - navigation.expand
    - navigation.instant
extra:
    mathjax:
        enable: true
    social:
        - icon: material/twitter
          link: https://x.com/Galaxea_AI
        - icon: material/github
          link: https://github.com/userguide-galaxea

nav:
  - Home: index.md
#   - About us: about_us/about_us.md
  - Galaxea Robot:
#       - About us: Introducing_Galaxea_Robot/introduction.md
      - A1: Introducing_Galaxea_Robot/product_info/A1.md
#       - R1: Introducing_Galaxea_Robot/product_info/R1.md
#       - X1: Introducing_Galaxea_Robot/product_info/X1.md
  - Galaxea A1 Guide:
      - Getting Started: Guide/A1/Getting_Started.md
      - Hardware Guide: Guide/A1/Hardware_Guide.md
      - Software Guide: Guide/A1/Software_Guide.md
#   - Galaxea R1 Guide:
#       - Getting Started: Guide/R1/Getting_Started.md
#       - R1 Hardware Guide: Guide/R1/A1_Hardware_Guide.md
#   - Galaxea X1 Guide:
#       - Getting Started: Guide/X1/Getting_Started.md
#       - X1 Hardware Guide: Guide/X1/A1_Hardware_Guide.md

extra_css:
  - styles.css
  - Introducing_Galaxea_Robot/simple_intro.css
  - Introducing_Galaxea_Robot/detail_intro.css

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js